//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagementDatalayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompanyManagementDatalayer.QueryResource", typeof(QueryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are present.
        /// </summary>
        public static string AllFieldsPresent {
            get {
                return ResourceManager.GetString("AllFieldsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id is Missing.
        /// </summary>
        public static string ClientIdMissing {
            get {
                return ResourceManager.GetString("ClientIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name is Missing.
        /// </summary>
        public static string ClientNameMissing {
            get {
                return ResourceManager.GetString("ClientNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Id is Missing.
        /// </summary>
        public static string CompanyIdMissing {
            get {
                return ResourceManager.GetString("CompanyIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name is Missing.
        /// </summary>
        public static string CompanyNameMissing {
            get {
                return ResourceManager.GetString("CompanyNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department ID is Missing.
        /// </summary>
        public static string DepartmenIDtMissing {
            get {
                return ResourceManager.GetString("DepartmenIDtMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name is Missing.
        /// </summary>
        public static string DepartmentNameMissing {
            get {
                return ResourceManager.GetString("DepartmentNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Id is Missing.
        /// </summary>
        public static string EmployeeIdMissing {
            get {
                return ResourceManager.GetString("EmployeeIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name is Missing.
        /// </summary>
        public static string EmployeeNameMissing {
            get {
                return ResourceManager.GetString("EmployeeNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee is neither projectManager nor Worker.
        /// </summary>
        public static string EmployeeNotInContext {
            get {
                return ResourceManager.GetString("EmployeeNotInContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeProject ID is Missing.
        /// </summary>
        public static string EmployeeProjectMapIDMissing {
            get {
                return ResourceManager.GetString("EmployeeProjectMapIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Salary is Missing.
        /// </summary>
        public static string EmployeeSalaryMissing {
            get {
                return ResourceManager.GetString("EmployeeSalaryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeTask ID is Missing.
        /// </summary>
        public static string EmpTaskIDMissing {
            get {
                return ResourceManager.GetString("EmpTaskIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joinning  Date is  Missing.
        /// </summary>
        public static string JoinDateMissing {
            get {
                return ResourceManager.GetString("JoinDateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete Active Project.
        /// </summary>
        public static string ProjectActive {
            get {
                return ResourceManager.GetString("ProjectActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Assign task as Project is Completed.
        /// </summary>
        public static string ProjectCompleted {
            get {
                return ResourceManager.GetString("ProjectCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Id is Missing.
        /// </summary>
        public static string ProjectIdMissing {
            get {
                return ResourceManager.GetString("ProjectIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name is Missing.
        /// </summary>
        public static string ProjectNameMissing {
            get {
                return ResourceManager.GetString("ProjectNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectTask ID is Missing.
        /// </summary>
        public static string ProjectTaskIDMissing {
            get {
                return ResourceManager.GetString("ProjectTaskIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID is Missing.
        /// </summary>
        public static string RoleIDMissing {
            get {
                return ResourceManager.GetString("RoleIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name is Missing.
        /// </summary>
        public static string RoleNameMissing {
            get {
                return ResourceManager.GetString("RoleNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Id is Missing.
        /// </summary>
        public static string StatusIdMissing {
            get {
                return ResourceManager.GetString("StatusIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Name is Missing.
        /// </summary>
        public static string StatusNameMissing {
            get {
                return ResourceManager.GetString("StatusNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the Active Task.
        /// </summary>
        public static string TaskActiveState {
            get {
                return ResourceManager.GetString("TaskActiveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Id is Missing.
        /// </summary>
        public static string TaskIdMissing {
            get {
                return ResourceManager.GetString("TaskIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name is Missing.
        /// </summary>
        public static string TaskNameMissing {
            get {
                return ResourceManager.GetString("TaskNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech Id is Missing.
        /// </summary>
        public static string TechIdMissing {
            get {
                return ResourceManager.GetString("TechIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Name is Missing.
        /// </summary>
        public static string TechNameMissing {
            get {
                return ResourceManager.GetString("TechNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology is used by more than 2 Projects and will not be deleted.
        /// </summary>
        public static string TechnologyCannotBeDeleted {
            get {
                return ResourceManager.GetString("TechnologyCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 4 Technologies are been Appiled for this Task Please update or delete.
        /// </summary>
        public static string TechnologyTaskExceeds {
            get {
                return ResourceManager.GetString("TechnologyTaskExceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TechProject ID is  Missing.
        /// </summary>
        public static string TechProjectIDMissing {
            get {
                return ResourceManager.GetString("TechProjectIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TechTask ID is Missing.
        /// </summary>
        public static string TechTaskMapIDMissing {
            get {
                return ResourceManager.GetString("TechTaskMapIDMissing", resourceCulture);
            }
        }
    }
}
